[package]
authors = ["sanjeev <sanjeevp@localhost>"]
edition = "2018"
name    = "stun"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio       = "1.3.0"
webrtc-stun = "0.1.13"
webrtc-util = "0.1.6"
